x = str("Hii Bro")
y = float(45.1)
z = int(45)
q = complex(4j)
w = range(7)
e = tuple(("Fruits", "Veggies", "Dry fruits", "Nuts"))
t = dict(Name="Ritesh", Age=23)
print(type(x))
print(type(y))
print(type(z))
print(type(q))
print(type(w))
print(type(e))
print(type(t))


